name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_PATH: "MauiApp1.sln"
  PROJECT_FILE: "MauiApp1/MauiApp1.csproj"

jobs:
  build-android:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '11'

    - name: Generate version number using date and run number
      shell: pwsh
      id: version-creator
      run: |
        $buildDay = Get-Date -Format "yyyy.Mdd"
        $ver = $buildDay + "." + $env:GITHUB_RUN_NUMBER + ".0"
        echo "APP_VERSION=$ver" >> $GITHUB_OUTPUT

    - name: Install MAUI workloads (required for GitHub-hosted runners)
      shell: pwsh
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

    - name: Restore NuGet packages at the project level
      shell: pwsh
      run: dotnet restore ${{ env.PROJECT_FILE }} -r win-x64 -p:PublishReadyToRun=true
    
    - name: Build Maui Android project
      shell: pwsh
      run: dotnet build ${{ env.PROJECT_FILE }} -c Release --no-restore -p:PublishTrimmed=False -p:PublishReadyToRun=true -r win-x64

    - name: Publish Android app
      shell: pwsh
      run: |
        dotnet publish ${{ env.PROJECT_FILE }} -f net7.0-android -c Release -p:AndroidPackageFormat=aab -o ${{ github.workspace }}/output

    - name: Upload Android artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-app
        path: ${{ github.workspace }}/output/*

  create-release:
    runs-on: ubuntu-latest
    needs: build-android
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download Android artifact
      uses: actions/download-artifact@v3
      with:
        name: android-app

    - name: Create Release
      id: create_release
      uses: actions/create-release@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version-creator.outputs.APP_VERSION }}
        release_name: Release ${{ steps.version-creator.outputs.APP_VERSION }}
        draft: false
        prerelease: false

    - name: Upload Asset to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/*.aab
        asset_name: myapp.aab
        asset_content_type: application/octet-stream
